version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [ backend ]
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on: [ postgres ]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      SCRIPT_NAME: /pgadmin
    ports:
      - "5050:80"
    networks: [ backend ]

networks:
  backend:

volumes:
  pgdata: