version: '3.8'

services:
  db:
    build: ./postgres
    image: kiphi/custom-postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pgnet

  pgadmin:
    build: ./pgadmin
    image: kiphi/custom-pgadmin:7
    container_name: pgadmin_ui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pgnet

volumes:
  db_data:

networks:
  pgnet:
