version: "3.8"

services:
  nginx:
    image: nginx:1.25.5
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

networks:
  backend: