version: '3.8'

services:
  nginx:
    build: .
    image: kiphi/custom-nginx:1.0
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    restart: always
    networks:
      - proxy_net

networks:
  proxy_net:
    driver: bridge